--Database Exploration

--Explore All Objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES

--Explore All Columns in the database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

--Exploreing all contries our customers come from
SELECT DISTINCT country FROM gold.dim_customers;

--Exploring  all categories 'The major Divisions'
SELECT DISTINCT category FROM gold.dim_products;

--Dimensions Exploration

SELECT DISTINCT category,subcategory FROM gold.dim_products;

SELECT DISTINCT category,subcategory,product_name FROM gold.dim_products;

--Date Exploration
-- Indentifying the earliest and latest dates

--Finding the date of the firat and last order
SELECT  
Min(order_date) AS first_order_date,
MAX(order_date) AS last_order_date,
DATEDIFF(year,MIN(order_date),MAX(order_date)) AS order_range_year,
DATEDIFF(month,MIN(order_date),MAX(order_date)) AS order_range_month
From gold.fact_sales;


--Finding the youngest and the oldest customer
SELECT
MAX(birthdate) AS youngest_birthdate,
DATEDIFF(year,MAX(birthdate),GETDATE()) AS youngest_age,
MIN(birthdate) AS oldest_birthdate,
DATEDIFF(year,MIN(birthdate),GETDATE()) AS oldest_age
FROM gold.dim_customers;


--Measures Exploration

--Calculating the key metric of the business(Big numbers)

--Highest Level of Aggreagtion(sum,avg)

--Finding the total sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales

--Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales

--Find the avg selling price
SELECT AVG(sales_amount) AS avg_sales FROM gold.fact_sales

--Find the Total number of orders
SELECT COUNT(order_number) AS Num_of_Orders FROM gold.fact_sales
SELECT COUNT(DISTINCT order_number) AS Num_of_Orders FROM gold.fact_sales

--Find the total number of products
SELECT COUNT(product_key) AS Num_of_products FROM gold.dim_products

SELECT COUNT(DISTINCT product_key) AS Num_of_products FROM gold.dim_products

--Find the total number of customers
SELECT COUNT(customer_key) AS Num_of_customers FROM gold.dim_customers
SELECT COUNT(DISTINCT customer_key) AS Num_of_customers FROM gold.dim_customers

--Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS Num_of_customers FROM gold.fact_sales

--Generating the report that shows all key metrics of the business
SELECT 'Total sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total quantity', SUM(quantity)  FROM gold.fact_sales
UNION ALL
SELECT 'Average_Price' ,AVG(sales_amount) FROM gold.fact_sales
UNION ALL 
SELECT 'Total_Nr_Orders' ,COUNT(DISTINCT order_number)  FROM gold.fact_sales
UNION ALL
SELECT 'Total_Nr_Products' ,COUNT(DISTINCT product_key)  FROM gold.dim_products
UNION ALL
SELECT 'Total_Nr_customers' ,COUNT(DISTINCT customer_key)  FROM gold.dim_customers

--Magnitude Analysis- compare the measure valuesby categories.
--It helps to understand the importance of different categories.

--Find tatal customers by countries
Select country,count(Distinct customer_key) AS Num_of_customers
From gold.dim_customers
Group by country
order by 2 desc;

--Find total customers by gender
Select gender,Count(Distinct customer_key) AS Num_of_customer
From gold.dim_customers
Group by gender
order by 2 desc;

--Find total products by category
select category,count(distinct product_id) AS Num_of_Products
From gold.dim_products
group by category
order by 2 desc;

--What is the Avg cost of each category ?
select category,avg(cost) as avg_cost
from gold.dim_products
group by category
order by 2 desc;

--What is the total revenue generated for each cateory?
select p.category,sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products  p
on p.product_key = f.product_key
group by p.category
order by total_revenue desc

--What is the total revenue generated by each customer?
select d.customer_key, d.first_name, sum(f.sales_amount) as revenue
from gold.fact_sales f
left join gold.dim_customers d
on f.customer_key=d.customer_key
group by d.customer_key,d.first_name
order by revenue desc

--what is the distribution of items sold across countries?
select c.country,sum(f.quantity) as total_sold_items
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by country
order by total_sold_items desc

--Ranking Analysis

--order the values of dimensions by measre
--Top N performers | Bottom N performers

--Which five product generate the highest revenue?

SELECT   TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
on p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

--What are the 5 worst performing products in terms of sales?
SELECT   TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
on p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC

--Which five subcategory generate the highest revenue?
SELECT   TOP 5
p.subcategory,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
on p.product_key = f.product_key
GROUP BY p.subcategory
ORDER BY total_revenue DESC

--What are the 5 worst performing subcategory in terms of sales?
SELECT   TOP 5
p.subcategory,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
on p.product_key = f.product_key
GROUP BY p.subcategory
ORDER BY total_revenue ASC

--using windows function
SELECT *
FROM (
SELECT   
p.subcategory,
SUM(f.sales_amount) total_revenue,
ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS rank_products
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
on p.product_key = f.product_key
GROUP BY p.subcategory
) t
WHERE rank_products<=5;


